######################################################################
# Automatically generated by qmake (2.01a) po 9 24 11:45:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += configDialog.h status.h timer.h
SOURCES += configDialog.cpp main.cpp status.cpp
RESOURCES += pomodoro.qrc
