######################################################################
# Automatically generated by qmake (2.01a) pá 10 5 10:43:10 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
HEADERS += configDialog.h connection.h log.h status.h timer.h
SOURCES += configDialog.cpp log.cpp main.cpp status.cpp
RESOURCES += pomodoro.qrc
